---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=999
      - TZ=Africa/Cairo
    volumes:
      - /home/docker/docker/sonarr/data:/config
      - /home/docker/docker/media/tv:/tv #optional
      - /home/docker/docker/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=999
      - TZ=Africa/Cairo
    volumes:
      - /home/docker/docker/radarr/data:/config
      - /home/docker/docker/media/movies:/movies #optional
      - /home/docker/docker/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=999
      - TZ=Africa/Cairo
      - WEBUI_PORT=8080
    volumes:
      - /home/docker/docker/qbittorrent/data:/config
      - /home/docker/docker/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=999
      - TZ=Africa/Cairo
    volumes:
      - /home/docker/docker/jackett/data:/config
      - /home/docker/docker/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=999
      - TZ=Africa/Cairo
    volumes:
      - /home/docker/docker/jellyfin/data:/config
      - /home/docker/docker/media/tv:/data/tvshows
      - /home/docker/docker/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
